RocketDan-2-team2/Toucheese-BE

- build.gradle
- src/main/java/com/example/toucheese_be/domain/studio/controller/StudioController.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/Studio.java
- src/main/resources/application.yml
ET-50
- oauth2, security 의존성 제거
- StudioController 기본 엔드포인트 구조 작성
<br>
> Feat/ET-50 : StudioController 기본 구조 작성

- src/main/generated/com/example/toucheese_be/domain/studio/entity/QItem.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/Item.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/constant/ItemCategory.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/constant/Region.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> Feat/item : 아이템 카테고리 컬럼 추가

- src/main/java/com/example/toucheese_be/domain/item/controller/ItemController.java
- src/main/java/com/example/toucheese_be/domain/item/dto/ItemDto.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Item.java
- src/main/java/com/example/toucheese_be/domain/item/repository/ItemRepository.java
- src/main/java/com/example/toucheese_be/domain/item/repository/ItemService.java
- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewDto.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/main/java/com/example/toucheese_be/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepositoryImpl.java
- src/main/java/com/example/toucheese_be/domain/studio/service/StudioService.java
- src/main/java/com/example/toucheese_be/domain/user/controller/UserController.java
- src/main/java/com/example/toucheese_be/domain/user/dto/UserDto.java
- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- src/main/java/com/example/toucheese_be/domain/user/repository/UserRepository.java
- src/main/java/com/example/toucheese_be/domain/user/service/UserService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 스프린트 3 세팅

- src/main/generated/com/example/toucheese_be/domain/item/entity/QItem.java
- src/main/generated/com/example/toucheese_be/domain/item/entity/QItemOption.java
- src/main/generated/com/example/toucheese_be/domain/item/entity/QOption.java
- src/main/generated/com/example/toucheese_be/domain/studio/entity/QStudio.java
- src/main/generated/com/example/toucheese_be/domain/studio/entity/QStudioImage.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Item.java
- src/main/java/com/example/toucheese_be/domain/item/entity/ItemOption.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Option.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioDto.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/Studio.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/StudioDutyDate.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/StudioImage.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/constant/DayType.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/constant/DutyType.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/constant/StudioImageType.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepositoryImpl.java
- ex) #ET-87~89
<br>
- 스튜디오 이미지 엔티티 작성
- 스튜디오 근무 시간 엔티티 작성
- 스튜디오 엔티티 수정
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> Feat/ET-87 : 스튜디오, 근무시간, 이미지 엔티티 작성

- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat/ET-91 : 유저 엔티티 작성

- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/test/java/com/example/toucheese_be/ToucheeseBeApplicationTests.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
Querydsl 오류를 해결하기 위해 그래들을 clean && build 함.
build 과정에서 test 관련 오류가 나왔고 test 관련 코드를 일단 주석 처리해둠.
- 특이 사항 2
<br><br>
> Querydsl 에러 처리 -1

- src/main/generated/com/example/toucheese_be/domain/studio/entity/QStudioDutyDate.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Item.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- #25 
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat/ET-99 스튜디오 리뷰 엔티티 작성

- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> Review 파일과 ReviewImageEntity 파일 간의 연관관계 수정

- src/main/generated/com/example/toucheese_be/domain/item/entity/QOption.java
- src/main/generated/com/example/toucheese_be/domain/studio/entity/QStudioDutyDate.java
- src/main/java/com/example/toucheese_be/domain/item/controller/ItemController.java
- src/main/java/com/example/toucheese_be/domain/item/dto/ItemDetailDto.java
- src/main/java/com/example/toucheese_be/domain/item/dto/ItemInfoDto.java
- src/main/java/com/example/toucheese_be/domain/item/dto/OptionDto.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Option.java
- src/main/java/com/example/toucheese_be/domain/item/repository/ItemOptionRepository.java
- src/main/java/com/example/toucheese_be/domain/item/service/ItemService.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioDto.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioInfoDto.java
- ex) #ET-93
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> Feat/ET-93 : 스튜디오 상품 상세 조회 기능 구현

- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewDto.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/main/java/com/example/toucheese_be/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioReviewDetailDto.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> ET-94 DTO 추가

- src/main/generated/com/example/toucheese_be/domain/item/entity/QItem.java
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReview.java
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReviewImageEntity.java
- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewDetailDto.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewDto.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/user/dto/UserProfileDto.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 리뷰 dto 작성

- src/main/generated/com/example/toucheese_be/domain/review/entity/QReview.java
- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/user/dto/UserProfileDto.java
- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 리뷰 상세 조회 구현 - 1

- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewImageDto.java
- src/main/java/com/example/toucheese_be/domain/review/repository/ReviewRepository.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioReviewDetailDto.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepository.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> ET-94 스튜디오 리뷰탭 이미지 상세 조회

- src/main/generated/com/example/toucheese_be/domain/review/entity/QReview.java
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReviewImageEntity.java
- src/main/generated/com/example/toucheese_be/domain/studio/entity/QStudioDutyDate.java
- src/main/java/com/example/toucheese_be/domain/item/controller/ItemController.java
- src/main/java/com/example/toucheese_be/domain/item/dto/ItemDto.java
- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- src/main/java/com/example/toucheese_be/domain/item/service/ItemService.java
- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewDto.java
- src/main/java/com/example/toucheese_be/domain/review/dto/ReviewImageDto.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/main/java/com/example/toucheese_be/domain/review/entity/ReviewImage.java
- src/main/java/com/example/toucheese_be/domain/review/service/ReviewService.java
- src/main/java/com/example/toucheese_be/domain/studio/controller/StudioController.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioInfoDto.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioReviewDetailDto.java
- src/main/java/com/example/toucheese_be/domain/studio/entity/StudioDutyDate.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepository.java
- src/main/java/com/example/toucheese_be/domain/studio/service/StudioService.java
- src/main/java/com/example/toucheese_be/domain/user/dto/UserProfileDto.java
- src/main/java/com/example/toucheese_be/global/error/ErrorCode.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 리뷰탭 구현 - 2

- src/main/generated/com/example/toucheese_be/domain/review/entity/QReview.java
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReviewImage.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioSearchFilterDto.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepositoryImpl.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 스튜디오 다중 지역 필터링 구현

- .github/workflows/CICD.yml
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReview.java
- src/main/generated/com/example/toucheese_be/domain/review/entity/QReviewImage.java
- src/main/java/com/example/toucheese_be/domain/review/controller/ReviewController.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> CICD.yml 생성

- src/main/java/com/example/toucheese_be/domain/studio/dto/StudioDto.java
- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepositoryImpl.java
- src/main/resources/application.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> Feat/ET-107 : querydsl 성능 문제 해결

- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- src/main/resources/application.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> ItemCategory 파일에 GROUP_PHOTO 추가

- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- src/main/resources/application.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> GROUP_PHOTO 수정

- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 아이템 카테고리 (세미화보) 추가

- src/main/java/com/example/toucheese_be/domain/item/entity/constant/ItemCategory.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 아이템 카테고리 (증명/여권사진) 수정

- src/main/java/com/example/toucheese_be/domain/studio/repository/StudioRepositoryImpl.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: StudioDto 조회 시 distinct() 조건 추가

- build.gradle
- src/main/java/com/example/toucheese_be/domain/email/config/EmailConfig.java
- src/main/java/com/example/toucheese_be/domain/email/controller/EmailController.java
- src/main/java/com/example/toucheese_be/domain/email/service/EmailService.java
- src/main/resources/application.yml
- ex) #ET-139
<br>
- "Toucheese" 구글 계정 개설 
- Java Mail 기본 설정 (build.gradle, application.yaml)
- `EmailConfig` 작성
<br>
> feat/ET-139 : Google SMTP 기본 설정

- src/main/java/com/example/toucheese_be/domain/reserve/entity/ReserveInfo.java
- src/main/java/com/example/toucheese_be/domain/reserve/entity/constant/NowReserveInfo.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
빠진 부분 없는지 && 이상한 부분 없는지 체크 부탁드립니다!
- 특이 사항 2
<br><br>
> feat/ET-123 예약 정보 엔티티 작성

- build.gradle
- src/main/generated/com/example/toucheese_be/domain/reserve/entity/QReserveInfo.java
- src/main/java/com/example/toucheese_be/domain/email/config/EmailConfig.java
- src/main/java/com/example/toucheese_be/domain/email/controller/EmailController.java
- src/main/java/com/example/toucheese_be/domain/email/service/EmailService.java
- src/main/java/com/example/toucheese_be/domain/reserve/entity/ReserveInfo.java
- src/main/resources/application.yml
- ex) #ET-140
- refactor: 성능 개선 등 리펙토링 및 폴더 구조 정리
<br>
- 잠시 smtp 관련 코드 주석
- reserveInfo 엔티티 수정 
<br>
> feat: smtp 주석, reserveInfo 엔티티 수정

- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> User 엔티티 파일에 연락처, 이메일 추가

- src/main/java/com/example/toucheese_be/domain/reserve/entity/ReserveInfo.java
- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat : User 엔티티에 필드 추가, ReserveInfo에 Option 연관관계 추가

- build.gradle
- src/main/generated/com/example/toucheese_be/domain/cart/entity/QCart.java
- src/main/generated/com/example/toucheese_be/domain/cart/entity/QCartItem.java
- src/main/generated/com/example/toucheese_be/domain/cart/entity/QCartItemOption.java
- src/main/java/com/example/toucheese_be/domain/cart/entity/Cart.java
- src/main/java/com/example/toucheese_be/domain/cart/entity/CartItem.java
- src/main/java/com/example/toucheese_be/domain/cart/entity/CartItemOption.java
- src/main/java/com/example/toucheese_be/domain/email/config/EmailConfig.java
- src/main/java/com/example/toucheese_be/domain/email/controller/EmailController.java
- src/main/java/com/example/toucheese_be/domain/email/service/EmailService.java
- src/main/resources/application.yml
- ex) #ET-140
<br>
- Cart 관련 엔티티 작성
> feat: Cart, CartItem, CartItemOption 엔티티 작성

- src/main/java/com/example/toucheese_be/domain/cart/controller/CartController.java
- src/main/java/com/example/toucheese_be/domain/cart/repository/CartItemOptionRepository.java
- src/main/java/com/example/toucheese_be/domain/cart/repository/CartItemRepository.java
- src/main/java/com/example/toucheese_be/domain/cart/repository/CartRepository.java
- src/main/java/com/example/toucheese_be/domain/cart/service/CartService.java
- ex) #ET-129
<br>
- Cart 관련 레포, 컨트롤러, 서비스 틀 작성
- Cart 상품 추가, 조회, 삭제, 수정
> feat: Cart 레포지토리, 컨트롤러, 서비스 틀 작성

- src/main/generated/com/example/toucheese_be/domain/reserve/entity/QReserveInfo.java
- src/main/generated/com/example/toucheese_be/domain/user/entity/QUser.java
- src/main/java/com/example/toucheese_be/domain/reserve/dto/ReservedDetailDto.java
- src/main/java/com/example/toucheese_be/domain/reserve/dto/ReservedItemDto.java
- src/main/java/com/example/toucheese_be/domain/reserve/dto/ReservedOptionDto.java
- src/main/java/com/example/toucheese_be/domain/reserve/dto/ReservedUserDto.java
- src/main/java/com/example/toucheese_be/domain/reserve/repository/ReserveInfoRepository.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat/ET-125 DTO 작성

- src/main/java/com/example/toucheese_be/domain/reserve/entity/ReserveInfo.java
- src/main/java/com/example/toucheese_be/domain/user/controller/AdminController.java
- src/main/java/com/example/toucheese_be/domain/user/service/AdminService.java
> feat: Admin 컨트롤러, 서비스 틀 작성

- src/main/java/com/example/toucheese_be/domain/auth/user/dto/UserDto.java
- src/main/java/com/example/toucheese_be/domain/order/controller/OrderController.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderDetailDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderUserDto.java
- src/main/java/com/example/toucheese_be/domain/order/entity/Order.java
- src/main/java/com/example/toucheese_be/domain/order/repository/OrderRepository.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 서비스 파일 구현, 컨트롤러 파일 구현, DTO 파일 구현

- src/main/generated/com/example/toucheese_be/domain/order/entity/QOrderItem.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/entity/OrderItem.java
- src/main/java/com/example/toucheese_be/domain/order/repository/OrderRepositoryImpl.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: main 업데이트

- src/main/java/com/example/toucheese_be/domain/auth/admin/dto/AdminOrderDto.java
- src/main/java/com/example/toucheese_be/domain/auth/admin/dto/AdminOrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/item/entity/Item.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderDetailDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderOptionDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderUserDto.java
- src/main/java/com/example/toucheese_be/domain/order/entity/Order.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- src/main/java/com/example/toucheese_be/domain/review/entity/Review.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/PageRequestDto.java
- src/main/java/com/example/toucheese_be/global/exception/GlobalException.java
- src/main/java/com/example/toucheese_be/global/rsData/RsData.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> fix: 빌드 오류 해결

- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> fix: 주문 생성 로직 수정

- src/main/java/com/example/toucheese_be/domain/auth/user/constant/SocialType.java
- src/main/java/com/example/toucheese_be/domain/auth/user/dto/oauth2/GoogleResponse.java
- src/main/java/com/example/toucheese_be/domain/auth/user/dto/oauth2/NaverResponse.java
- src/main/java/com/example/toucheese_be/domain/auth/user/dto/oauth2/OAuth2Response.java
- src/main/java/com/example/toucheese_be/domain/auth/user/entity/PrincipalDetails.java
- src/main/java/com/example/toucheese_be/domain/auth/user/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/example/toucheese_be/domain/auth/user/jwt/JwtTokenDto.java
- src/main/java/com/example/toucheese_be/domain/auth/user/jwt/JwtTokenUtils.java
- src/main/java/com/example/toucheese_be/domain/auth/user/service/PrincipalDetailsService.java
- src/main/java/com/example/toucheese_be/domain/auth/user/service/PrincipalOAuth2UserService.java
- src/main/java/com/example/toucheese_be/domain/studio/dto/response/StudioDutyDateDto.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 로그인 API 구현, 근무시간 조회 isHoliday 누락 수정

- build.gradle
- src/main/java/com/example/toucheese_be/domain/user/controller/JwtTokenController.java
- src/main/java/com/example/toucheese_be/domain/user/controller/UserController.java
- src/main/java/com/example/toucheese_be/domain/user/jwt/JwtTokenUtils.java
- src/main/java/com/example/toucheese_be/domain/user/jwt/TokenRequestDto.java
- src/main/java/com/example/toucheese_be/domain/user/jwt/TokenResponseDto.java
- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- src/main/java/com/example/toucheese_be/domain/user/service/RefreshTokenService.java
- src/main/java/com/example/toucheese_be/global/config/RedisConfig.java
- src/main/java/com/example/toucheese_be/global/config/WebSecurityConfig.java
- src/main/java/com/example/toucheese_be/global/error/ErrorCode.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- ex) #ET-1
- AWS ElastiCache Redis 연동
- 토큰 재발급 시 Redis 에 RefreshToken 저장 
- Dockerfile 을 작성하여 Docker hub로 부터 받은 이미지를 EC2 서버에서 컨테이너로 실행할 수 있도록 환경 구성
> feat: AWS ElastiCache Redis 연동, Dockerfile 작성

- .github/workflows/docker-image.yml
- Dockerfile
- ex) #ET-1
<br>
- 지속적 통합을 위해 CI 도입 (도커 이미지 생성)
- 수동 통합으로 우선 결정
> feat: Github Actions CI 코드 작성

- .github/workflows/CICD.yml
- .github/workflows/docker-image.yml
- src/main/java/com/example/toucheese_be/domain/user/jwt/JwtTokenFilter.java
- src/main/java/com/example/toucheese_be/global/error/ErrorCode.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: docker-image.yml 수정, accessToken ErrorCode 추가

- .github/workflows/docker-image.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: docker-image.yml 수정

- .github/workflows/docker-image.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: docker-image.yml 수정 - 2

- .github/workflows/docker-image.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: docker-image.yml 수정 - 3

- .github/workflows/docker-image.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: docker-image.yml 수정 - 4

- src/main/java/com/example/toucheese_be/domain/order/controller/OrderController.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- src/main/java/com/example/toucheese_be/global/exception/AlreadyCancelledException.java
- src/main/java/com/example/toucheese_be/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/toucheese_be/global/exception/OrderNotFoundException.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 예외 처리 && 예약 취소 Controller && Service 작성 완료

- src/main/java/com/example/toucheese_be/domain/order/controller/OrderController.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderDetailDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderOptionDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderUserDto.java
- src/main/java/com/example/toucheese_be/domain/order/entity/Order.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat/ET-174 && featET-175 진행 중&완료

- src/main/java/com/example/toucheese_be/domain/order/dto/OrderItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/dto/OrderScheduleItemDto.java
- src/main/java/com/example/toucheese_be/domain/order/entity/Order.java
- src/main/java/com/example/toucheese_be/domain/order/repository/OrderRepository.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: ET-176 - n+1 문제 해결+ Po stman 성공

- src/main/java/com/example/toucheese_be/domain/order/controller/OrderController.java
- src/main/java/com/example/toucheese_be/domain/order/dto/request/OrderRequestDto.java
- src/main/java/com/example/toucheese_be/domain/order/repository/OrderRepository.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat/ET-177 && ET-178->틀 만들기

- src/main/java/com/example/toucheese_be/domain/order/repository/OrderRepositoryImpl.java
- src/main/java/com/example/toucheese_be/domain/user/dto/response/AdminOrderDto.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 어드민 페이지 예약 상태 정보 포함, 최근 예약순 정렬

- src/main/java/com/example/toucheese_be/domain/user/jwt/JwtTokenFilter.java
- src/main/java/com/example/toucheese_be/global/config/WebSecurityConfig.java
- src/main/resources/application.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> refactor: Swagger 적용 URL 수정

- Dockerfile
- src/main/java/com/example/toucheese_be/domain/order/controller/OrderController.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> 오류 수정 && Dockerfile 수정

- src/main/java/com/example/toucheese_be/domain/order/entity/Order.java
- src/main/java/com/example/toucheese_be/domain/order/service/OrderService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 일정 탭 수정

- src/main/generated/com/example/toucheese_be/domain/user/entity/QUser.java
- src/main/java/com/example/toucheese_be/domain/user/controller/AdminController.java
- src/main/java/com/example/toucheese_be/domain/user/controller/JwtTokenController.java
- src/main/java/com/example/toucheese_be/domain/user/dto/request/UpdateUserDto.java
- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- src/main/java/com/example/toucheese_be/domain/user/fcm/FcmConfig.java
- src/main/java/com/example/toucheese_be/domain/user/fcm/FcmNotificationRequestDto.java
- src/main/java/com/example/toucheese_be/domain/user/fcm/FcmNotificationService.java
- src/main/java/com/example/toucheese_be/domain/user/service/AdminService.java
- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- src/main/java/com/example/toucheese_be/global/config/WebSecurityConfig.java
- src/main/resources/application.yml
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 유저 추가 정보 입력

- src/main/java/com/example/toucheese_be/domain/user/entity/User.java
- src/main/java/com/example/toucheese_be/domain/user/repository/UserRepository.java
- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- src/main/java/com/example/toucheese_be/global/error/ErrorCode.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 유저 추가정보 기입 닉네임 중복 체크

- src/main/java/com/example/toucheese_be/domain/user/controller/UserController.java
- src/main/java/com/example/toucheese_be/domain/user/dto/request/NicknameCheck.java
- src/main/java/com/example/toucheese_be/domain/user/jwt/JwtTokenFilter.java
- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- src/main/java/com/example/toucheese_be/global/config/WebSecurityConfig.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 유저 추가정보 기입 닉네임 중복 체크 -2

- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 추가 정보 입력 if-else 문 수정

- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 재로그인 시 username 필드 업데이트

- src/main/java/com/example/toucheese_be/domain/user/service/PrincipalDetailsService.java
- ex) #ET-1
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: SocialLoginDto Builder nickname 필드 수정
